name: Generate Snake Animation

on:
  schedule:
    # Jalankan otomatis setiap hari pukul 6 pagi UTC
    - cron: "0 6 * * *"
  workflow_dispatch: # Manual trigger dari GitHub UI

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # generate the Snake animation
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # push ke branch "output" untuk menampilkan hasil di GitHub Pages
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
